# -*- coding: utf-8 -*-
"""Tokenizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z492htGsa2tVxxu4zdj4xKTLccmuscTH
"""

text = "Ｕｎｉｃｏｄｅ! 🅤🅝🅘🅒🅞🅓🅔‽ 🇺‌🇳‌🇮‌🇨‌🇴‌🇩‌🇪! 😄 The very name strikes fear and awe into the hearts of programmers worldwide. We all know we ought to “support Unicode” in our software (whatever that means—like using wchar_t for all the strings, right?). But Unicode can be abstruse, and diving into the thousand-page Unicode Standard plus its dozens of supplementary annexes, reports, and notes can be more than a little intimidating. I don’t blame programmers for still finding the whole thing mysterious, even 30 years after Unicode’s inception."

#Enable the UTF-8 encoding to the current text
tokens = list(map(int, text.encode('utf-8')))

tokens

"""#Byte Pair Encoding Algorithm
Step - 1 => Loop through all the pairs in the encoded_str list

Step - 2 => Add the pairs as a tuple to a dictionary along with its frequency

Step - 3 => Sort the dictionary in respective to the frequency of the pairs

Step - 4 => Replace the highest frequency of pairs with the next available idx

Step - 5 => Loop through this replacement logic until you get the desired output
"""

#Step - 1 => Loop through all the pairs in the encoded_str list
#Step - 2 => Add the pairs as a tuple to a dictionary along with its frequency
def get_stats(ids):
  counts = {}
  for i in range(len(ids) - 1):
    pair = (ids[i], ids[i + 1])
    counts[pair] = counts.get(pair, 0) + 1

  return counts

stats = get_stats(tokens)

#Step - 3 => Sort the dictionary in respective to the frequency of the pairs
sorted_count = sorted(((v, k) for k, v in stats.items()), reverse = True)

top_pair = max(stats, key = stats.get)

#Step - 4 => Replace the highest frequency of pairs with the next available idx
def merge(ids, pair, idx):

  new_ids = []

  skip = False

  for i in range(len(ids)):

    if skip:
        skip = False
        continue

    if i < len(ids) - 1 and ids[i] == pair[0] and ids[i + 1] == pair[1]:
        new_ids.append(idx)
        skip = True  # This successfully skips the next element

    else:
        new_ids.append(ids[i])

  return new_ids

new_tokens = merge(tokens, list(top_pair), 256)

print(len(tokens), len(new_tokens))

#Step - 5 => Loop through this replacement logic until you get the desired output

#Precompute the merges with the help of current tokens
vocab_size = 276

ids = list(tokens)

merges = {}

for new_idx in range(256, vocab_size):
  stats = get_stats(ids)
  top_pair = max(stats, key = stats.get)
  ids = merge(ids, list(top_pair), new_idx)
  merges[top_pair] = new_idx

print(merges)
print("tokens length", len(tokens))
print("ids length", len(ids))
print(f"compression ratio, {len(tokens) / len(ids):.2f}X")

#Encode & Decode it back
vocab = {idx: bytes([idx]) for idx in range(256)}

for (p0, p1), idx in merges.items():
  vocab[idx] = vocab[p0] + vocab[p1]

#decode the list of tokens given
def decode(ids):
  '''given a list of ids return a string'''
  curr_tokens = b"".join(vocab[id] for id in ids)

  return curr_tokens.decode("utf-8", errors="replace")

print(decode([275]))

def encode(text):

  tokens = list(text.encode("utf-8"))

  while len(tokens) >= 2:

    stats = get_stats(tokens)
    min_pair = min(stats, key = lambda p : merges.get(p, float('inf')))

    #If there is no pair then it will return the first element
    if min_pair not in merges:
      break

    idx = merges[min_pair]

    tokens = merge(tokens, list(min_pair), idx)

    return tokens

#Inference check
print(encode("hello world!"))

print(decode(encode("hello world!")))

"""The initial paragarph of text is our training code, for which we find out the merges dictionary

Once the merges has been trained and all other functionalities holds responsbility of what they do, they carry out their job

The "Hello World" is the inference code, which we use it against the merges (obtained from the training code) to get the result of vectorized / 1D of numbers
"""